erDiagram
  Verb {
      Int id
    String name
    String description
    }
  

  Person {
      Int id
    String fullname
    Boolean published
    }
  

  Relations {
  
    }
  
    Relations o{--|| Person : "PersonA"
    Relations o{--|| Person : "PersonB"
    Relations o{--|| Verb : "Verb"
